# =========================================
# DOCKER COMPOSE - DESENVOLVIMENTO LOCAL
# =========================================

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    container_name: linkchartapi-dev
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./storage/logs:/var/www/storage/logs
      - ./storage/app:/var/www/storage/app
      - vendor_cache:/var/www/vendor
      - ./.env.local:/var/www/.env
    depends_on:
      - database
      - redis
    networks:
      - linkchartnet
    environment:
      - CONTAINER_ROLE=app
      - DB_HOST=database
      - REDIS_HOST=redis
      - DB_CONNECTION=pgsql
      - DB_DATABASE=link_chart
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - REDIS_CLIENT=phpredis

  database:
    image: postgres:15-alpine
    container_name: linkchartdb-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: link_chart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - linkchartnet

  redis:
    image: redis:7-alpine
    container_name: linkchartredis-dev
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    ports:
      - "6380:6379"
    networks:
      - linkchartnet

  # Nginx para desenvolvimento (opcional)
  nginx:
    image: nginx:alpine
    container_name: linkchartnginx-dev
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public:ro
    depends_on:
      - app
    networks:
      - linkchartnet

volumes:
  postgres_data_dev:
  redis_data_dev:
  vendor_cache:

networks:
  linkchartnet:
    driver: bridge
