services:
  app:
    image: php:8.2-fpm-alpine
    container_name: linkchartapi
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage/logs:/var/www/storage/logs
      - ./storage/app:/var/www/storage/app
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    command: >
      sh -c "
        apk add --no-cache postgresql-dev redis git unzip curl autoconf gcc g++ make &&
        docker-php-ext-install pdo_pgsql &&
        pecl install redis &&
        docker-php-ext-enable redis &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        composer install --no-dev --optimize-autoloader &&
        php artisan migrate --force &&
        php artisan optimize &&
        php-fpm
      "
    depends_on:
      - database
      - redis
    networks:
      - linkchartnet

  nginx:
    image: nginx:alpine
    container_name: linkchartnginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - app
    networks:
      - linkchartnet

  database:
    image: postgres:15-alpine
    container_name: linkchartdb
    restart: unless-stopped
    environment:
      POSTGRES_DB: linkchartprod
      POSTGRES_USER: linkchartuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - linkchartnet

  redis:
    image: redis:7-alpine
    container_name: linkchartredis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - linkchartnet

volumes:
  postgres_data:
  redis_data:

networks:
  linkchartnet:
    driver: bridge
