<?php

namespace App\Http\Controllers\Analytics;

use App\Contracts\Analytics\LinkAnalyticsOrchestratorInterface;
use App\Contracts\Analytics\TemporalAnalyticsInterface;
use App\DTOs\Analytics\AnalyticsFilters;
use App\Http\Controllers\BaseController;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * Analytics controller for per-link advanced analytics endpoints.
 *
 * Extends BaseController to inherit findOwnedLink, linkNotFound, and serverError.
 * Depends on LinkAnalyticsOrchestratorInterface (injected, resolved from the
 * concrete LinkAnalyticsOrchestrator since R-13) and TemporalAnalyticsInterface
 * for the merged temporal endpoint.
 *
 * Routes (all under api.auth:api + verified middleware, prefix /api/analytics/link/{linkId}):
 *   GET /api/analytics/link/{linkId}/dashboard     → getLinkDashboardData
 *   GET /api/analytics/link/{linkId}/comprehensive → getLinkAnalytics
 *   GET /api/analytics/link/{linkId}/geographic    → getGeographicAnalytics
 *   GET /api/analytics/link/{linkId}/insights      → getBusinessInsights
 *   GET /api/analytics/link/{linkId}/temporal      → getTemporalAnalytics
 *   GET /api/analytics/link/{linkId}/audience      → getAudienceAnalytics
 *
 * Cross-mount note: GET /api/links/{id}/analytics is physically defined in the
 * links route group (routes/api.php line 96) but is handled by this controller's
 * getLinkSummaryAnalytics action, not by LinkController.
 *
 * Heatmap data was folded into getGeographicAnalytics in commit 00e6a3f; there
 * is no longer a dedicated /heatmap endpoint.
 */
class AnalyticsController extends BaseController
{
    public function __construct(
        private LinkAnalyticsOrchestratorInterface $analyticsService,
        private TemporalAnalyticsInterface $temporalService
    ) {}

    /**
     * GET /api/analytics/link/{linkId}/comprehensive
     *
     * Return comprehensive analytics for a single link by delegating to
     * LinkAnalyticsOrchestratorInterface::getComprehensiveLinkAnalytics.
     *
     * Middleware: api.auth:api, verified
     * Auth: required
     * Owner check: yes — uses findOwnedLink.
     *
     * Response shape: { success: true, data: ComprehensiveAnalytics }
     */
    public function getLinkAnalytics(int $linkId): JsonResponse
    {
        try {
            $link = $this->findOwnedLink($linkId);
            if (! $link) {
                return $this->linkNotFound();
            }

            $analytics = $this->analyticsService->getComprehensiveLinkAnalytics($linkId);

            return response()->json([
                'success' => true,
                'data' => $analytics,
            ]);
        } catch (\Exception $e) {
            return $this->serverError('Erro ao buscar analytics do link.', $e);
        }
    }

    /**
     * GET /api/analytics/link/{linkId}/geographic
     *
     * Return detailed geographic analytics (country, city, continent breakdowns)
     * with heatmap data folded in (heatmap was merged here in commit 00e6a3f).
     * Delegates to LinkAnalyticsOrchestratorInterface::getLinkGeographicAnalytics,
     * which returns a { data, meta } payload that is forwarded directly.
     *
     * Middleware: api.auth:api, verified
     * Auth: required
     * Owner check: yes — uses findOwnedLink.
     *
     * Response shape: { success: true, data: GeographicData, meta: GeographicMeta }
     */
    public function getGeographicAnalytics(int $linkId): JsonResponse
    {
        try {
            $link = $this->findOwnedLink($linkId);
            if (! $link) {
                return $this->linkNotFound();
            }

            $payload = $this->analyticsService->getLinkGeographicAnalytics($linkId);

            return response()->json([
                'success' => true,
                'data' => $payload['data'],
                'meta' => $payload['meta'],
            ]);
        } catch (\Exception $e) {
            return $this->serverError('Erro ao buscar analytics geográficos.', $e);
        }
    }

    /**
     * GET /api/analytics/link/{linkId}/insights
     *
     * Return automated business insights generated by the InsightsAnalyticsService
     * Strategy pipeline (8 generators). Payload includes insights array, summary,
     * and analytics_data (retention, session_depth, traffic_sources) consumed by
     * the frontend useInsightsData hook.
     *
     * Middleware: api.auth:api, verified
     * Auth: required
     * Owner check: yes — uses findOwnedLink.
     *
     * Response shape: { success: true, data: InsightsPayload }
     */
    public function getBusinessInsights(int $linkId): JsonResponse
    {
        try {
            $link = $this->findOwnedLink($linkId);
            if (! $link) {
                return $this->linkNotFound();
            }

            $insights = $this->analyticsService->getLinkInsightsAnalytics($linkId);

            return response()->json([
                'success' => true,
                'data' => $insights,
            ]);
        } catch (\Exception $e) {
            return $this->serverError('Erro ao buscar insights de negócio.', $e);
        }
    }

    /**
     * GET /api/analytics/link/{linkId}/temporal
     *
     * Return unified temporal analytics merging base data (clicks_by_hour,
     * clicks_by_day_of_week, etc.) from the orchestrator with advanced data
     * (weekly_trends, monthly_trends, peak_analysis, timezone_analysis with
     * computed percentages, heatmap_data, daily_timeline, device_by_period)
     * from TemporalAnalyticsInterface::getAdvancedTemporalAnalytics. Consumed
     * by the frontend useTemporalData hook.
     *
     * Middleware: api.auth:api, verified
     * Auth: required
     * Owner check: yes — uses findOwnedLink.
     *
     * Response shape: { success: true, data: { ...baseData, advanced: AdvancedTemporal } }
     */
    public function getTemporalAnalytics(int $linkId): JsonResponse
    {
        try {
            $link = $this->findOwnedLink($linkId);
            if (! $link) {
                return $this->linkNotFound();
            }

            // 1. Buscar dados base (clicks_by_hour, clicks_by_day_of_week, etc.)
            $baseData = $this->analyticsService->getLinkTemporalAnalytics($linkId);

            // 2. Buscar dados avançados (weekly_trends, monthly_trends, peak_analysis, timezone_analysis)
            $advancedData = $this->temporalService->getAdvancedTemporalAnalytics($linkId);

            // 3. Enriquecer timezone analysis com percentuais
            $enrichedTimezones = $this->enrichTimezoneAnalysis($advancedData['timezone_analysis'] ?? []);

            // 4. Merge estruturado - compatível com tipos existentes
            $unifiedData = array_merge($baseData, [
                'advanced' => [
                    'weekly_trends' => $advancedData['weekly_trends'] ?? [],
                    'monthly_trends' => $advancedData['monthly_trends'] ?? [],
                    'peak_analysis' => $advancedData['peak_analysis'] ?? [],
                    'timezone_analysis' => $enrichedTimezones,
                    'heatmap_data' => $advancedData['heatmap_data'] ?? [],
                    'daily_timeline' => $advancedData['daily_timeline'] ?? [],
                    'device_by_period' => $advancedData['device_by_period'] ?? [],
                ],
            ]);

            return response()->json([
                'success' => true,
                'data' => $unifiedData,
            ]);
        } catch (\Exception $e) {
            return $this->serverError('Erro ao buscar analytics temporais.', $e);
        }
    }

    /**
     * GET /api/analytics/link/{linkId}/audience
     *
     * Return audience analytics (device breakdown, browser distribution,
     * OS distribution, mobile/desktop/tablet split, engagement metrics).
     * Delegates to LinkAnalyticsOrchestratorInterface::getLinkAudienceAnalytics.
     *
     * Middleware: api.auth:api, verified
     * Auth: required
     * Owner check: yes — uses findOwnedLink.
     *
     * Response shape: { success: true, data: AudienceAnalytics }
     */
    public function getAudienceAnalytics(int $linkId): JsonResponse
    {
        try {
            $link = $this->findOwnedLink($linkId);
            if (! $link) {
                return $this->linkNotFound();
            }

            $analytics = $this->analyticsService->getLinkAudienceAnalytics($linkId);

            return response()->json([
                'success' => true,
                'data' => $analytics,
            ]);
        } catch (\Exception $e) {
            return $this->serverError('Erro ao buscar analytics de audiência.', $e);
        }
    }

    /**
     * GET /api/analytics/link/{linkId}/dashboard?hours=0
     *
     * Return dashboard analytics for a single link combining basic metrics with
     * chart data. The optional `hours` query parameter filters the time window:
     * accepted values are 1, 24, 168, 720 (0 = all time, the default).
     *
     * Middleware: api.auth:api, verified
     * Auth: required
     * Owner check: yes — uses findOwnedLink.
     *
     * Response shape: { success: true, data: DashboardAnalytics }
     *
     * @param  Request  $request  Query param: hours (int, one of 1|24|168|720|0).
     */
    public function getLinkDashboardData(Request $request, int $linkId): JsonResponse
    {
        try {
            $userId = auth()->guard('api')->id();

            if (! $userId) {
                return response()->json(['error' => 'Usuário não autenticado.'], 401);
            }

            $link = $this->findOwnedLink($linkId);
            if (! $link) {
                return $this->linkNotFound();
            }

            $validHours = [1, 24, 168, 720];
            $hours = in_array((int) $request->query('hours'), $validHours, true)
                ? (int) $request->query('hours')
                : 0;

            $filters = $hours > 0
                ? new AnalyticsFilters(dateFrom: now()->subHours($hours)->toDateTimeString())
                : null;

            $analytics = $this->analyticsService->getLinkDashboardAnalytics($linkId, $filters);

            return response()->json([
                'success' => true,
                'data' => $analytics,
            ]);
        } catch (\Exception $e) {
            return $this->serverError('Erro ao buscar dados do dashboard do link.', $e);
        }
    }

    /**
     * GET /api/links/{id}/analytics
     *
     * Legacy analytics endpoint cross-mounted from the /api/links route group.
     * Although the URL looks like a LinkController route, this action lives in
     * AnalyticsController and is wired in routes/api.php via:
     *   Route::get('/{id}/analytics', [AnalyticsController::class, 'getLinkSummaryAnalytics'])
     *
     * Returns aggregate statistics using SQL (no full Click model load): total
     * and unique clicks, avg daily clicks, conversion rate, 30-day timeline,
     * top countries/devices/referrers. Returns a zero-click stub when there are
     * no clicks yet.
     *
     * Middleware: api.auth:api, verified
     * Auth: required
     * Owner check: yes — uses findOwnedLink.
     *
     * Response shape: raw JSON — not wrapped by NormalizeApiResponse.
     *   Zero clicks: { has_sufficient_data: false, total_clicks: 0, link_info }
     *   With clicks:  { total_clicks, unique_visitors, avg_daily_clicks,
     *                   conversion_rate, clicks_over_time, clicks_by_country,
     *                   clicks_by_device, clicks_by_referer, link_info }
     *
     * @param  string  $id  Numeric link ID (enforced by route constraint [0-9]+).
     */
    public function getLinkSummaryAnalytics(string $id): JsonResponse
    {
        try {
            $link = $this->findOwnedLink((int) $id);
            if (! $link) {
                return $this->linkNotFound();
            }

            $totalClicks = (int) $link->getAttribute('clicks');

            if ($totalClicks == 0) {
                return response()->json([
                    'has_sufficient_data' => false,
                    'message' => 'Analytics disponíveis após o primeiro clique no link',
                    'total_clicks' => 0,
                    'link_info' => [
                        'id' => $link->id,
                        'slug' => $link->slug,
                        'title' => $link->title,
                        'original_url' => $link->original_url,
                        'shorted_url' => $link->getShortedUrl(),
                        'created_at' => $link->created_at,
                        'is_active' => $link->is_active,
                        'expires_at' => $link->expires_at,
                    ],
                ]);
            }

            $base = fn () => \App\Models\Click::where('link_id', $link->id);

            // Unique IPs for unique_visitors
            $uniqueVisitors = $base()->distinct('ip')->count('ip');

            // avg_daily_clicks: total / days since creation (min 1)
            $daysSinceCreated = max(1, now()->diffInDays($link->created_at));
            $avgDailyClicks = round($totalClicks / $daysSinceCreated, 1);
            $conversionRate = $uniqueVisitors > 0
                ? round(($totalClicks / $uniqueVisitors) * 100, 1).'%'
                : '0%';

            // clicks_over_time: last 30 days, one row per day — SQL DATE aggregation
            $isSqlite = DB::connection()->getDriverName() === 'sqlite';
            $dateExpr = $isSqlite ? "strftime('%Y-%m-%d', created_at)" : "TO_CHAR(created_at, 'YYYY-MM-DD')";

            $clicksRaw = $base()
                ->where('created_at', '>=', now()->utc()->subDays(29)->startOfDay())
                ->selectRaw("$dateExpr AS day, COUNT(*) AS total")
                ->groupByRaw($dateExpr)
                ->pluck('total', 'day');

            $clicksOverTime = [];
            for ($i = 29; $i >= 0; $i--) {
                $date = now()->utc()->subDays($i)->format('Y-m-d');
                $clicksOverTime[] = ['date' => $date, 'clicks' => (int) ($clicksRaw[$date] ?? 0)];
            }

            // clicks_by_country
            $clicksByCountry = $base()
                ->whereNotNull('country')
                ->selectRaw('country, COUNT(*) AS clicks')
                ->groupBy('country')
                ->orderByDesc('clicks')
                ->limit(10)
                ->get()
                ->map(fn ($r) => ['country' => $r->country, 'clicks' => $r->clicks])
                ->values()
                ->toArray();

            // clicks_by_device
            $clicksByDevice = $base()
                ->whereNotNull('device')
                ->selectRaw('device, COUNT(*) AS clicks')
                ->groupBy('device')
                ->orderByDesc('clicks')
                ->limit(10)
                ->get()
                ->map(fn ($r) => ['device' => $r->device, 'clicks' => $r->clicks])
                ->values()
                ->toArray();

            // clicks_by_referer: group by raw referer in SQL, then re-aggregate by host in PHP
            $rawReferrers = $base()
                ->whereNotNull('referer')
                ->where('referer', '!=', '-')
                ->where('referer', '!=', '')
                ->selectRaw('referer, COUNT(*) AS clicks')
                ->groupBy('referer')
                ->orderByDesc('clicks')
                ->limit(100)
                ->pluck('clicks', 'referer');

            // Add "Direct" count
            $directCount = $base()
                ->where(function ($q) {
                    $q->whereNull('referer')
                        ->orWhere('referer', '-')
                        ->orWhere('referer', '');
                })
                ->count();

            $hostTotals = [];
            if ($directCount > 0) {
                $hostTotals['Direct'] = $directCount;
            }
            foreach ($rawReferrers as $referer => $clicks) {
                $host = parse_url($referer, PHP_URL_HOST) ?: 'Unknown';
                $hostTotals[$host] = ($hostTotals[$host] ?? 0) + $clicks;
            }
            arsort($hostTotals);
            $clicksByReferer = array_map(
                fn ($host, $clicks) => ['referer' => $host, 'clicks' => $clicks],
                array_keys(array_slice($hostTotals, 0, 10)),
                array_slice($hostTotals, 0, 10)
            );

            return response()->json([
                'total_clicks' => $totalClicks,
                'unique_visitors' => $uniqueVisitors,
                'avg_daily_clicks' => $avgDailyClicks,
                'conversion_rate' => $conversionRate,
                'clicks_over_time' => $clicksOverTime,
                'clicks_by_country' => $clicksByCountry,
                'clicks_by_device' => $clicksByDevice,
                'clicks_by_referer' => $clicksByReferer,
                'link_info' => [
                    'id' => $link->id,
                    'slug' => $link->slug,
                    'title' => $link->title,
                    'original_url' => $link->original_url,
                    'shorted_url' => $link->getShortedUrl(),
                    'created_at' => $link->created_at,
                    'is_active' => $link->is_active,
                    'expires_at' => $link->expires_at,
                ],
            ]);
        } catch (\Exception $e) {
            return $this->serverError('Erro ao buscar analytics do link.', $e);
        }
    }

    /**
     * Enrich a timezone analysis array by computing percentage shares.
     *
     * @param  array  $timezones  Array of [ 'name' => string, 'clicks' => int ] entries.
     * @return array Same entries with an added 'percentage' float field (0–100, 2 dp).
     */
    private function enrichTimezoneAnalysis(array $timezones): array
    {
        if (empty($timezones)) {
            return [];
        }

        // Calcular total de cliques
        $total = array_sum(array_column($timezones, 'clicks'));

        // Enriquecer cada timezone com percentual
        return array_map(function ($tz) use ($total) {
            return [
                'name' => $tz['name'] ?? 'Unknown',
                'clicks' => $tz['clicks'] ?? 0,
                'percentage' => $total > 0 ? round(($tz['clicks'] / $total) * 100, 2) : 0,
            ];
        }, $timezones);
    }
}
